### ISSUE TITLE
Circular import involving Demes

### ISSUE THREAD

**Issue by apragsdale** [MomentsLD/moments#118]
While local tests and github actions are passing, bioconda complains about circular imports involving the spectrum and LD statistics classes (which have `from_demes()` functions) and the Demes module.

We need to make imports linear, which might mean removing the "from_demes()" functions in the Spectrum and LDstats classes.

Below is the traceback for their failed import.

```
20:24:00 BIOCONDA INFO (OUT) Traceback (most recent call last):
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/test_tmp/run_test.py", line 2, in <module>
20:24:00 BIOCONDA INFO (OUT)     import moments
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/__init__.py", line 15, in <module>
20:24:00 BIOCONDA INFO (OUT)     from . import Godambe
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Godambe.py", line 6, in <module>
20:24:00 BIOCONDA INFO (OUT)     from . import Inference
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Inference.py", line 13, in <module>
20:24:00 BIOCONDA INFO (OUT) import: 'moments'
20:24:00 BIOCONDA INFO (OUT)     from . import Misc, Numerics
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Misc.py", line 11, in <module>
20:24:00 BIOCONDA INFO (OUT)     from . import Spectrum_mod
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Spectrum_mod.py", line 35, in <module>
20:24:00 BIOCONDA INFO (OUT)     import moments.Demes as Demes
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Demes/__init__.py", line 1, in <module>
20:24:00 BIOCONDA INFO (OUT)     from . import Demes, Inference, DemesUtil
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/Demes/Demes.py", line 13, in <module>
20:24:00 BIOCONDA INFO (OUT)     import moments.LD
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/LD/__init__.py", line 1, in <module>
20:24:00 BIOCONDA INFO (OUT)     from . import (
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/LD/Demographics1D.py", line 2, in <module>
20:24:00 BIOCONDA INFO (OUT)     from moments.LD.LDstats_mod import LDstats
20:24:00 BIOCONDA INFO (OUT)   File "/opt/conda/conda-bld/moments_1680898094328/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/moments/LD/LDstats_mod.py", line 12, in <module>
20:24:00 BIOCONDA INFO (OUT)     import moments.Demes as Demes
20:24:00 BIOCONDA INFO (OUT) AttributeError: module 'moments' has no attribute 'Demes'
```

**Comment by apragsdale** [comment]
Closed by #120
