### ISSUE TITLE
Building fails with "builld" module

### ISSUE THREAD

**Issue by molpopgen** [MomentsLD/moments#166]
The module fails to build with [build](https://pypi.org/project/build/).

To reproduce:

```sh
gh repo clone momentsld/moments
cd moments
python -m venv ~/tmp/venv
soruce ~/tmp/venv/bin/activate
python -m pip install build
python -m build .
```

The error message is:

```
Traceback (most recent call last):
  File "/home/kevin/tmp/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/kevin/tmp/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevin/tmp/venv/lib64/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 87, in <module>
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
    module_list, module_metadata = create_extension_list(
                                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/tmp/build-env-_0t9d1_j/lib64/python3.12/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
    raise ValueError(error_msg)
ValueError: 'moments/Jackknife.pyx' doesn't match any files

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

I'm guessing that the build is copying files around and is unable to get the paths right.

This should be fixed before #165 and #91 because using `build` to generate the source dist and wheels will be useful for those.

**Comment by apragsdale** [comment]
Closed by #167
